# Generated by Django 2.2.27 on 2024-05-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrosurvey',
            name='deadline',
            field=models.DateField(db_column='deadline', verbose_name='Határidő'),
        ),
    ]
