# Generated by Django 2.2.27 on 2024-05-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240509_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydroSurveyFlowDirection',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.DateField(db_column='name', verbose_name='Áramlási irány')),
            ],
            options={
                'verbose_name': 'Hydro Survey Flow Direction',
                'db_table': 'hydrosurvey_flow_direction',
                'managed': True,
            },
        ),
    ]
