# Generated by Django 2.2.27 on 2024-05-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_hydrosurveyflowdirection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HydroSurveyFlowDirection',
        ),
        migrations.AlterField(
            model_name='hydrosurvey',
            name='deadline',
            field=models.DateTimeField(db_column='deadline', verbose_name='Határidő'),
        ),
    ]
