# Generated by Django 2.2.27 on 2024-05-10 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240510_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydroSurveyFlowDirection',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50, verbose_name='Áramlási irány')),
            ],
            options={
                'verbose_name': 'Hydro Survey Flow Direction',
                'db_table': 'hydrosurvey_flow_direction',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='hydrosurvey',
            name='deadline',
            field=models.DateField(db_column='deadline', verbose_name='Határidő'),
        ),
        migrations.AlterField(
            model_name='hydrosurvey',
            name='flow_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HydroSurveyFlowDirection'),
        ),
    ]
