# Generated by Django 2.2.27 on 2024-05-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240510_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turbine',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('vortex', models.CharField(db_column='name', max_length=250)),
                ('turbine_type', models.DateTimeField(db_column='created_at')),
                ('continous', models.DateField(db_column='deadline')),
                ('water_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProjectStatus')),
            ],
            options={
                'verbose_name': 'Turbine',
                'db_table': 'turbine',
                'managed': True,
            },
        ),
    ]
