# Generated by Django 2.2.27 on 2024-05-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_turbine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine',
            name='continous',
            field=models.CharField(db_column='continous', max_length=3),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='turbine_type',
            field=models.CharField(db_column='turbine_type', max_length=50),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='vortex',
            field=models.IntegerField(db_column='vortex'),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='water_level',
            field=models.IntegerField(db_column='water_level'),
        ),
    ]
