# Generated by Django 2.2.27 on 2024-05-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20240515_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbine',
            name='name',
            field=models.CharField(db_column='name', default=1, max_length=50),
            preserve_default=False,
        ),
    ]
