# Generated by Django 2.2.27 on 2024-05-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_turbine_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Efficiency',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('ρ', models.IntegerField(db_column='rho', default=1000)),
                ('vortex', models.IntegerField(db_column='vortex')),
                ('turbine_type', models.CharField(db_column='turbine_type', max_length=50)),
                ('water_level', models.IntegerField(db_column='water_level')),
                ('continous', models.CharField(db_column='continous', max_length=3)),
            ],
            options={
                'verbose_name': 'Efficiency',
                'db_table': 'turbine_efficiency',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='hydrosurvey',
            name='flow_direction',
            field=models.CharField(choices=[('N', 'Észak'), ('E', 'Kelet'), ('S', 'Dél'), ('W', 'Nyugat')], db_column='flow_direction', max_length=10, verbose_name='Áramlás iránya'),
        ),
        migrations.DeleteModel(
            name='HydroSurveyFlowDirection',
        ),
    ]
