# Generated by Django 2.2.27 on 2024-05-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_task_orthophoto_bands'),
        ('app', '0009_auto_20240517_1220'),
    ]

    operations = [
    ]
