# Generated by Django 2.2.27 on 2024-05-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20240524_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='efficiency',
            options={'managed': True, 'verbose_name': 'Efficiency', 'verbose_name_plural': 'Efficiencies'},
        ),
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'managed': True, 'verbose_name': 'Project Status', 'verbose_name_plural': 'Project Statuses'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'managed': True, 'verbose_name': 'Report'},
        ),
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'managed': True, 'verbose_name': 'Task Status', 'verbose_name_plural': 'Task Stasuses'},
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='completion_value',
            field=models.FloatField(db_column='completion_value', default=0),
        ),
    ]
